"""PipelineConfig: all parameters needed to reproduce a pipeline run."""

import math
from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Union


@dataclass
class PipelineConfig:
    # IIR bandpass
    iir_l_freq: float = 1.0
    iir_h_freq: float = 50.0
    iir_order: int = 4
    # ASR
    asr_backend: str = "asrpy"
    asr_cutoff: float = 20.0
    asr_calibration_seconds: float = 120.0
    asr_calibration_npz: Optional[str] = None
    chunk_size: int = 1000
    # ORICA
    orica_ff_profile: str = "cooling"
    orica_block_size_white: int = 8
    orica_block_size_ica: int = 8
    orica_lambda_0: float = 0.995
    orica_gamma: float = 0.6
    orica_num_subgaussian: int = 0
    orica_tau_const: float = float("inf")
    # ICLabel
    icalabel_threshold: float = 0.7
    # Seconds between ICLabel runs in the online pipeline (0 = every chunk)
    classify_interval_s: float = 30.0

    def to_yaml(self, path: Union[str, Path]) -> None:
        """Write an annotated, human-readable YAML file."""
        tau = ".inf" if math.isinf(self.orica_tau_const) else self.orica_tau_const
        npz_val = "null" if self.asr_calibration_npz is None else repr(self.asr_calibration_npz)
        lines = [
            "# pyorica PipelineConfig",
            "# Generated by PipelineConfig.to_yaml(). Edit values, then pass this",
            "# file to run_all_subjects.py --config <this_file>.",
            "#",
            "# Defaults match the reference experiments (SN_Driveasrpy20_2min_70).",
            "",
            "# ── IIR bandpass filter ──────────────────────────────────────────────",
            f"iir_l_freq: {self.iir_l_freq}            # lower cutoff (Hz)",
            f"iir_h_freq: {self.iir_h_freq}           # upper cutoff (Hz)",
            f"iir_order: {self.iir_order}              # filter order (higher = sharper rolloff, more ringing)",
            "",
            "# ── ASR (Artifact Subspace Reconstruction) ──────────────────────────",
            f'asr_backend: "{self.asr_backend}"     # "asrpy" (default) or "meegkit"',
            f"asr_cutoff: {self.asr_cutoff}          # SD multiplier; higher = less aggressive cleaning",
            f"asr_calibration_seconds: {self.asr_calibration_seconds}  # session lead-in for ORICA warm-start",
            f"asr_calibration_npz: {npz_val}  # external ASR calib NPZ; {{subject}} ok",
            f"chunk_size: {self.chunk_size}  # samples per simulated-real-time pipeline chunk",
            "",
            "# ── ORICA (Online Recursive ICA) ────────────────────────────────────",
            f'orica_ff_profile: "{self.orica_ff_profile}"       # forgetting factor schedule',
            f"orica_block_size_white: {self.orica_block_size_white}       # samples per RLS whitening update",
            f"orica_block_size_ica: {self.orica_block_size_ica}         # samples per ICA weight update",
            f"orica_lambda_0: {self.orica_lambda_0}       # initial forgetting factor λ₀ ∈ (0, 1)",
            f"orica_gamma: {self.orica_gamma}           # cooling decay rate (used when ff_profile=cooling)",
            f"orica_num_subgaussian: {self.orica_num_subgaussian}    # ICs assumed sub-Gaussian (0 = all super-Gaussian)",
            f"orica_tau_const: {tau}        # local stationarity window (samples); .inf = global",
            "",
            "# ── ICLabel artifact classifier ─────────────────────────────────────",
            f"icalabel_threshold: {self.icalabel_threshold}      # probability threshold ∈ [0, 1]",
            f"classify_interval_s: {self.classify_interval_s}     # seconds between ICLabel runs (0 = every chunk)",
        ]
        Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")

    @classmethod
    def from_yaml(cls, path: Union[str, Path]) -> "PipelineConfig":
        """Load config from a YAML file (annotated or plain)."""
        import dataclasses
        import yaml
        with open(path, encoding="utf-8") as f:
            d = yaml.safe_load(f)
        if d.get("orica_tau_const") == ".inf":
            d["orica_tau_const"] = float("inf")
        if d.get("asr_calibration_npz") in ("None", "none"):
            d["asr_calibration_npz"] = None
        known = {f.name for f in dataclasses.fields(cls)}
        d = {k: v for k, v in d.items() if k in known}
        return cls(**d)
