"""PipelineConfig: all parameters needed to reproduce a pipeline run."""

import math
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Union


@dataclass
class PipelineConfig:
    # IIR bandpass
    iir_l_freq: float = 1.0
    iir_h_freq: float = 50.0
    iir_order: int = 4
    # ASR
    asr_backend: str = "asrpy"
    asr_cutoff: float = 20.0
    asr_calibration_seconds: float = 120.0
    # ORICA
    orica_ff_profile: str = "cooling"
    orica_block_size_white: int = 8
    orica_block_size_ica: int = 8
    orica_lambda_0: float = 0.995
    orica_gamma: float = 0.6
    orica_num_subgaussian: int = 0
    orica_tau_const: float = float("inf")
    # ICLabel
    icalabel_threshold: float = 0.7
    # Apply CAR + 1-100 Hz bandpass to the classification input (matches
    # ICLabel's documented training assumptions; off by default to match the
    # legacy ORICA reference).
    icalabel_apply_car_bandpass: bool = False
    # Label-selection policy: False = fail-open (reject only known artifact
    # labels), True = fail-closed (reject everything except brain/other).
    icalabel_use_protect_list: bool = False
    # Seconds between ICLabel runs in the online pipeline (0 = every chunk)
    classify_interval_s: float = 0.0
    # Benchmark simulation chunk size (samples per pipeline step)
    chunk_size: int = 1000

    def to_yaml(self, path: Union[str, Path]) -> None:
        """Write an annotated, human-readable YAML file.

        Each parameter is preceded by a comment describing its role and valid
        values. The file can be edited and passed back via --config.
        """
        tau = ".inf" if math.isinf(self.orica_tau_const) else self.orica_tau_const
        lines = [
            "# pyorica PipelineConfig",
            "# Generated by PipelineConfig.to_yaml(). Edit values, then pass this",
            "# file to run_all_subjects.py --config <this_file>.",
            "#",
            "# Defaults match the reference experiments (SN_Driveasrpy20_2min_70).",
            "",
            "# ── IIR bandpass filter ──────────────────────────────────────────────",
            "# Online Butterworth bandpass applied to every chunk before ASR.",
            f"iir_l_freq: {self.iir_l_freq}            # lower cutoff (Hz)",
            f"iir_h_freq: {self.iir_h_freq}           # upper cutoff (Hz)",
            f"iir_order: {self.iir_order}              # filter order (higher = sharper rolloff, more ringing)",
            "",
            "# ── ASR (Artifact Subspace Reconstruction) ──────────────────────────",
            '# "asrpy" matches the reference experiments and uses stateful chunk-by-',
            '# chunk processing (R/Zi/cov). "meegkit" is available for comparison.',
            f'asr_backend: "{self.asr_backend}"     # "asrpy" (default) or "meegkit"',
            f"asr_cutoff: {self.asr_cutoff}          # SD multiplier; higher = less aggressive cleaning",
            f"asr_calibration_seconds: {self.asr_calibration_seconds}  # seconds of IIR-filtered data used to calibrate ASR",
            "",
            "# ── ORICA (Online Recursive ICA) ────────────────────────────────────",
            '# Forgetting factor profile: "cooling" (λ decreases over time),',
            '# "constant", or "adaptive".',
            f'orica_ff_profile: "{self.orica_ff_profile}"       # forgetting factor schedule',
            f"orica_block_size_white: {self.orica_block_size_white}       # samples per RLS whitening update",
            f"orica_block_size_ica: {self.orica_block_size_ica}         # samples per ICA weight update",
            f"orica_lambda_0: {self.orica_lambda_0}       # initial forgetting factor λ₀ ∈ (0, 1)",
            f"orica_gamma: {self.orica_gamma}           # cooling decay rate (used when ff_profile=cooling)",
            f"orica_num_subgaussian: {self.orica_num_subgaussian}    # ICs assumed sub-Gaussian (0 = all super-Gaussian)",
            f"orica_tau_const: {tau}        # local stationarity window (seconds); steady-state λ = 1-exp(-1/(tau×sfreq)); .inf = global",
            "",
            "# ── ICLabel artifact classifier ─────────────────────────────────────",
            "# ICs with artifact probability above this threshold are zeroed.",
            "# Artifact classes: muscle, eye, heart, line noise, channel noise.",
            f"icalabel_threshold: {self.icalabel_threshold}      # probability threshold ∈ [0, 1]",
            f"icalabel_apply_car_bandpass: {str(self.icalabel_apply_car_bandpass).lower()}"
            "  # apply CAR + bandpass before classifying (default: false)",
            f"icalabel_use_protect_list: {str(self.icalabel_use_protect_list).lower()}"
            "      # false = fail-open, true = fail-closed protect-list",
            f"classify_interval_s: {self.classify_interval_s}     # seconds between ICLabel runs (0 = every chunk)",
            "",
            "# ── Benchmark simulation ─────────────────────────────────────────────",
            f"chunk_size: {self.chunk_size}             # samples per pipeline step in simulated real-time",
        ]
        Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")

    @classmethod
    def from_yaml(cls, path: Union[str, Path]) -> "PipelineConfig":
        """Load config from a YAML file (annotated or plain)."""
        import dataclasses
        import yaml
        with open(path, encoding="utf-8") as f:
            d = yaml.safe_load(f)
        if d.get("orica_tau_const") == ".inf":
            d["orica_tau_const"] = float("inf")
        known = {f.name for f in dataclasses.fields(cls)}
        d = {k: v for k, v in d.items() if k in known}
        return cls(**d)
